# Generated by Django 3.2.25 on 2024-09-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=254)),
                ('item', models.TextField()),
                ('other', models.TextField()),
            ],
        ),
    ]
