# Generated by Django 3.2.25 on 2024-09-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20240915_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='item',
        ),
    ]
