# Generated by Django 3.2.25 on 2024-09-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_return_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
