# Generated by Django 3.2.25 on 2024-09-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_return_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='reasons',
            field=models.CharField(blank=True, choices=[('Wrong color', 'Wrong color'), ('Wrong items', 'Wrong items'), ('Order did not fit', 'Order did not fit'), ('Order arrived too late', 'Order arrived too late'), ('Order was not as described', 'Order was not as described'), ('Other (if other please specify down below)', 'Other (if other please specify down below)')], default='Wrong color', max_length=254, null=True),
        ),
    ]
