# Generated by Django 3.2.25 on 2024-09-12 09:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_productreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReview',
            new_name='Review',
        ),
    ]
