# Generated by Django 3.2.25 on 2024-09-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_review_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shoes_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
